### PR TITLE
Home page mockup #6

### PR DESCRIPTION
**Pull request by luisvillara**
Hello @isysd, this is the branch with HUGO, follow the README instructions to run the project ;) I hope you like it.

### CODE REVIEW

**Comment by isysd** [comment]
Thanks for the clean PR @luisvillara! It took me 30 seconds to deploy this on http://isysd.github.io/ for us to gather feedback. There are a number of small things out of alignment, for instance.

**Comment by isysd** [comment]
FYI I deployed this so fast using the build script in master:

https://github.com/deginner/tigoctm/blob/master/deploy.sh

Please put this file back in to your merge. :)

**Comment by luisvillara** [comment]
@isysd the deploy.sh file was uploaded ;)

Please feel free to comment the small things that you are talking about the alignment.

**Comment by d3brouille** [comment]
@luisvillara, thanks for the pr.

1. I note that much of the copy is located in `src/hugo/layouts/index.html`.  One of the reasons Hugo was chosen is because we want to leverage the fact that it supports writing content as markdown.  The site should be implemented such that the copy is located as markdown files in `src/hugo/content/*.md`
2. the roadmap infographic needs some work, here's what it looks like at 100% on firefox:

**Comment by isysd** [comment]
Going to merge this so that Glen can start editing copy.

**Pull request merged**
