### PR TITLE
Git guild/master

### PR DESCRIPTION
**Pull request by glenkow**
Added benefits for section 5

### CODE REVIEW

**Comment by indieinc** [comment]
# Testing #12
 
## Issues
This version of benefits.md includes HTML, which will interfere with Hugo's Markdown processing.

## Screenshots
Using the changes from #12, I rendered the homepage with Hugo.

#### HTML included in benefits.md:

benefits_test_1

#### HTML removed from benefits.md:

test_benefits_2

***

[Hugo supports shortcodes within .md content files.](https://gohugo.io/extras/shortcodes/) That may be the way to go.

**Comment by glenkow** [comment]
HTML should not be required, I am new to MD and trying to follow the conventions already in the skeleton files, but feel free to make any required changes to layout.

**Comment by indieinc** [comment]
The MD formatting looks good, as does the copy. It's a learning process with Hugo and MD for both of us. Saw a bit of HTML in the file and noticed that Hugo only parsed the Markdown properly when the HTML was removed, which led me to the Hugo documentation. Hope it was of some interest, at least.

**Comment by glenkow** [comment]
Yes, was just reading the documentation you sent. Very interesting. Also trying to figure out hugo :-).

**Comment by isysd** [comment]
@indieinc thank you for the commits! Please be aware that @glenkow and other non-technical people are helping us, including using the unfamiliar Github and Markdown. Not that you haven't been, but please be respectful of people's roles, and specialities. We're here to compliment each other. :+1:

**Pull request merged**
